### ISSUE TITLE
Navy Upload Product Page Issue

### ISSUE THREAD

**Issue by mtuttle03** [AMTuttle02/HomeTeamCreativity#163] opened 2023-11-10 14:53 UTC
So, the uploading navy preview has been fixed, thank you. But when I uploaded a test product, called "test" I uploaded it in a navy long sleeve, then I went to the end of the products page, clicked on the product and it blanks out and goes back to the entire products page first page, instead of opening the individual product description and info. Not sure why, thanks!

**Comment by AMTuttle02** [comment] 2023-11-19 22:38
Hello. This is not a bug. Since you only have 1 product named "Test" and you did not enter a crewneck color, the product will fail. You must have at least 1 color per style, such as navy for tshirt, navy for long sleeve, black for crewneck, and navy for hoodie. However, this can be spread across multiple designs with the same name. Such as a black design named "Test" and a white design named "Test". Hope that answers your question. If you add another design or add a crewneck color, you will see the bug is resolved. Please reopen the request if further action is needed.

**Comment by AMTuttle02** [comment] 2023-11-19 22:39
Please move item to "Ready for test" if the solution is working correctly.

**Comment by mtuttle03** [comment] 2023-11-20 16:02
Ok, so the upload is working now, I realized I did it wrong, oops, but I found new bug, maybe user error, idk :)

On Navy uploaded designs, such as the one called test, I search test and the image fails to show, I have a screenshot I will try to attach. I tried this multiple times. 

![Image](https://github.com/AMTuttle02/HomeTeamCreativity/assets/149885763/ca20f4ef-0e31-4a3e-a1d8-7a09f7a18fe7)

**Comment by AMTuttle02** [comment] 2023-11-20 17:05
Yes, this was a big bug. Search page should be fixed now on test instance. Feel free to add test design back to test site as I had to delete it. Verify the search page is working correctly before moving this issue into "Ready for Test"

**Closed as completed by AMTuttle02** 2023-11-20 17:05 UTC
Labels: bug

**Comment by mtuttle03** [comment] 2023-11-20 17:22
Thanks!
